config/routes.rb
Rails.application.routes.draw do
  resources :moments

  get '/m/:hash' => 'moments#card' 

  devise_for :users
  root 'login#index'
  get '*path' => redirect('/')

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moment.rb
class Moment < ApplicationRecord
    belongs_to :user
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post
  has_many :moment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @themes = Theme.all
    moments = Moment.all.where(user_id: current_user)
    @moments = moments.last(4).sort_by{|m| m.updated_at}.reverse

    if !user_signed_in?
      render layout: "navbarLogin"
    else 
      render layout: "navbarHome"
    end

    
  end
end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController
  before_action :set_moment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:card]

  require 'digest'

  # GET /moments
  # GET /moments.json
  def index
    moments = Moment.all.where(user_id: current_user)
    @moments = moments.sort_by{|m| m.updated_at}.reverse
    render layout: "navbarHome"
  end

  # GET /moments/1
  # GET /moments/1.json
  
  def show
    redirect_to root_path
  end

  def card
    @moment = hashed_moment
    p '#######$$$$$$$%%%%%%%%$$$$$$######&&&&&&&&@@@@@@&&#&$&&@&'
    p @moment

    render layout: "card"
  end

  # GET /moments/new
  def new
    @moment = Moment.new
  end

  # GET /moments/1/edit
  def edit
    @moment = set_moment
  end

  # POST /moments
  # POST /moments.json
  def create
    p params
    if params[:occasion] == 'birthday'
      p '#######$$$$$$$%%%%%%%%$$$$$$######&&&&&&&&@@@@@@&&#&$&&@&'
      p params[:occasion]
      p '#######$$$$$$$%%%%%%%%$$$$$$######&&&&&&&&@@@@@@&&#&$&&@&'
    elsif params[:occasion] == 'graduation'
      p '#######$$$$$$$%%%%%%%%$$$$$$######&&&&&&&&@@@@@@&&#&$&&@&'
      p params[:occasion]
      p '#######$$$$$$$%%%%%%%%$$$$$$######&&&&&&&&@@@@@@&&#&$&&@&'
    elsif params[:occasion] == 'farewell'
      p '#######$$$$$$$%%%%%%%%$$$$$$######&&&&&&&&@@@@@@&&#&$&&@&'
      p params[:occasion]
      p '#######$$$$$$$%%%%%%%%$$$$$$######&&&&&&&&@@@@@@&&#&$&&@&'
    end

    @moment = Moment.new(title:"", to_name:"", from_name:"", occasion: params[:occasion], description3: params[:description], user: current_user)
    @moment.save

    respond_to do |format|
      if @moment.save

        moment_id = @moment.id.to_s
        p 'moment id'
        p moment_id
        Digest::SHA256.hexdigest 'moment_id'
        sha256 = Digest::SHA256.new
        hashed_id = sha256.hexdigest moment_id
        p 'hashed id'
        p hashed_id
        @moment.card_url = hashed_id
        @moment.save
        
        format.html { redirect_to edit_moment_path(@moment), notice: 'Moment was successfully created.' }
        format.json { render :show, status: :created, location: @moment }
      else
        format.html { render :new }
        format.json { render json: @moment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moments/1
  # PATCH/PUT /moments/1.json
  def update
    # respond_to do |format|
      if @moment.update(moment_params)
        # format.html { redirect_to @moment, notice: 'Moment was successfully updated.' }
        # format.json { render :show, status: :ok, location: @moment }
        render :json => @moment, status: :ok
      else
        # format.html { render :edit }
        # format.json { render json: @moment.errors, status: :unprocessable_entity }
        render :json => @moment.errors, status: :unprocessable_entity
      end
    # end
  end

  # DELETE /moments/1
  # DELETE /moments/1.json
  def destroy
    @moment.destroy
    respond_to do |format|
      format.html { redirect_to moments_url, notice: 'Moment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moment
      p'PARMARMMSMDMMSDMSMDMD'
      p params
      # moments = Moment.all.where(user_id: current_user)
      @moment = Moment.find(params[:id])
      # p @moment.user_id;
      if @moment.user_id == current_user.id
        p 'NANIIIIIIIIIIIII'
        p @moment
      else 
        redirect_to root_path
      end
      # if .length == 0
      #   redirect_to root_path
      # else 
        
      # end

    end

    def hashed_moment
      # @moment = Moment.where(audio_url: params[:hash])[0]
      @moment = Moment.where(card_url: params[:hash])[0]

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moment_params
      # params.require(:moment).permit(:title, :to_name, :from_name, :description, :image_url, :audio_url)
      params.permit(:title, :to_name, :from_name, :description, :image_url, :audio_url, :occasion, :card_url, :description2, :description3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moments_helper.rb
module MomentsHelper
end

app/helpers/onepage_helper.rb
module OnepageHelper
end

app/views/application/_card.html.erb
<%
=begin%>
 <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
  <a class="navbar-brand" href="/">Moments</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav> 
<%
=end%>

<a href="/"><h2 style="color:#212529">Moments</h2></a>

app/views/application/_navbar2.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Test</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/application/_navbarHome.html.erb
<!-- Vertical navbar -->
<div class="vertical-nav bg-white" id="sidebar">
  <div class="py-4 px-3 mb-4 bg-light">
    <div class="media d-flex align-items-center"><img src="https://ichef.bbci.co.uk/news/624/cpsprodpb/503C/production/_104304502_be53e1b5-279a-460d-963a-b70c8025926f.jpg" alt="..." width="100px" height="75px" class="mr-3 rounded-circle img-thumbnail shadow-sm">
      <div class="media-body">
        <h4 class="m-0">
          <%=current_user.email.split('@')[0].capitalize %>
        </h4>
        <%
=begin%>
 <p class="font-weight-light text-muted mb-0">Add pic here</p> 
<%
=end%>
      </div>
    </div>
  </div>

  <ul class="nav flex-column bg-white mb-0">
    <li class="nav-item sideNavItem">
      <a href="/" class="nav-link text-dark font-italic bg-light">
          Home
      </a>
    </li>
    <li class="nav-item sideNavItem">
      <a href="/moments" class="nav-link text-dark font-italic bg-light">
          All Your Designs
      </a> 

    </li>
    
    <li class="nav-item sideNavItem">
      <%= link_to 'Sign out', destroy_user_session_url, method: :delete, class: 'nav-link text-dark font-italic bg-light px-3' %>
    </li>
  </ul>

</div>
<!-- End vertical navbar -->

app/views/application/_navbarLogin.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
  <a class="navbar-brand" href="/">Moments</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <%
=begin%>
 <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li> 
<%
=end%>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Login', new_user_session_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
      </li>
    </ul>

  </div>
</nav>

app/views/application/_navbarMain.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
  <a class="navbar-brand" href="/">Moments</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/moments">All Your Designs</a>
      </li>
    </ul>

    <ul class="navbar-nav">

      <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_url, method: :delete, class: 'nav-link' %>
        </li>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    
  </head>

  <body>
    <%= render "navbarMain" %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= yield %>

    
  </body>
</html>

app/views/layouts/card.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    
  </head>

  <body>
    <%= render "card" %>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    
  </head>

  <body>
    <%= render "navbarLogin" %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= yield %>
    
  </body>
</html>

app/views/layouts/navbarHome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="16x16" href="./images/favicon.png">


    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

  </head>

  <body>
    <%= render "navbarHome" %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/navbarLogin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap" 
    rel="stylesheet">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon.png">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    
  </head>

  <body>
    <%= render "navbarLogin" %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= yield %>
    
  </body>
</html>

app/views/layouts/sidebar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>

  <body>
    <%= render "navbar2" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/login/index.html.erb
<% if user_signed_in? %>


<!-- Page content holder -->
<div class="page-content" id="content">
  <!-- Toggle button -->
  <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm"><i class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold"><img class="d-flex align-items-center" src="https://img.icons8.com/android/50/000000/menu.png" width="20rem" height="20rem"></small></button>

  <!-- Demo content -->
  <div class="indexTopHolder">

    <div>
      <h2 class="display-4 text-white indexTitle topMoments"><span class="mx-2" id="word">This is</span> Moments</h2>
    </div>

    <div class="search__container" id="searchBar">
      <p class="search__title">
          Search for a theme
      </p>
      <input class="search__input form-control homepage-searchbar mx-auto" style="width:540px" id="myInput" type="text" placeholder="">
    </div>

    <div>
      <p class="lead text-white mb-0">Create memories that last a lifetime</p>
    </div>
  </div>
  
  <div class="indexHeaders">
    <h3>Create a moment</h3>
    <h6> > </h6>
  </div>

  <div class="createContainer">
    <% @themes.each do |t| %>
    <div class='indexCardWrap'>
      <%= form_with scope: :moment, url: moments_path, local: true do |form| %>
        <input name="occasion" type="hidden" value=<%=t[:occasion]%> />
        <input name="description" type="hidden" value=<%=t[:description]%> />
        <%= form.submit "Begin", :type => :image, :src => t[:url], :formtarget => "_blank" %>
        <p class="indexCardTitle"><%=t[:title]%></p>
      <% end %>
    </div>
    <% end %>
  </div>

  <div class="separator"></div>

  <div class="indexAllDesigns indexHeaders">
    <h3>Your Designs</h3>
    <h6><a href="/moments"> See all > </a></h6>
  </div>

  <div class="designContainer">

      <% @moments.each do |moment| %>
        <div class='indexCardWrap2'>

          <h2><%= moment.title %></h2>

          <p><strong><%= moment.occasion.capitalize %></strong></p>

          <a href=<%="/m/#{moment.card_url}"%> target="_blank"><button class="btn btn-outline-light">View Card</button></a>
          
          <a href=<%=edit_moment_path(moment)%>><button class="btn btn-outline-light">Edit</button></a>
          
        </div>
      <% end %>
  </div>

  <%
=begin%>
 <div class="indexAllDesigns indexHeaders">
    <h3><a href="/moments">Your Designs</a></h3>
    <h5> > </h5>
  </div> 
<%
=end%>

</div>
<!-- End demo content -->


  


<% else %>

  <style>
    body {background-color: white;}
    /* #navbarNav {background-color: white;} */
  </style>

  
  <div class="content lp-top-cont">
    <section id="home" class="col-4">
	      <div class="home-content">
          <h3>Deliver amazing moments.</h3>
          <h3>Cherish them forever.</h3>
          <p>With Moments, you can easily create fun, animated content, in a matter of minutes. Sign up for free today.</p>
        </div>
        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
    </section>
    <aside class="col-8">
    </aside>
  </div>


  <%
=begin%>
 <div>
    <h2>All Designs to choose from</h2>
  </div> 
<%
=end%>

 <%= render "devise/registrations/new" %>   










<% end %>

app/views/moments/_form.html.erb
<%= form_with(model: moment, local: true) do |form| %>
  <% if moment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(moment.errors.count, "error") %> prohibited this moment from being saved:</h2>

      <ul>
        <% moment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :to_name %>
    <%= form.text_field :to_name %>
  </div>

  <div class="field">
    <%= form.label :from_name %>
    <%= form.text_field :from_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :audio_url %>
    <%= form.text_field :audio_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moments/edit.html.erb
<%= content_tag :div,
    id: 'currentMoment',
    data: @moment.to_json do %>
<% end %> 

<%= javascript_pack_tag 'hello_react' %> 
<%= stylesheet_pack_tag 'hello_react' %>

app/views/moments/new.html.erb
<h1>New Moment</h1>


<%= render 'form', moment: @moment %> 


<%
=begin%>
 <%= javascript_pack_tag 'hello_react' %>
<%= stylesheet_pack_tag 'hello_react' %>  
<%
=end%>


<%= link_to 'Back', moments_path %>

app/views/moments/x.html.erb
<p id="notice"><%= notice %></p>

<% if @moment === nil %>
	<p>No such thing bruh </p>
	<% controller.redirect_to '/' %>

<% else %>
	<p>
	<strong>ID:</strong>
	<%= @moment.id %>
	</p>

	<p>
	<strong>Title:</strong>
	<%= @moment.title %>
	</p>

	<p>
	<strong>To name:</strong>
	<%= @moment.to_name %>
	</p>

	<p>
	<strong>From name:</strong>
	<%= @moment.from_name %>
	</p>

	<p>
	<strong>Description:</strong>
	<%= @moment.description %>
	</p>

	<p>
	<strong>Image url:</strong>
	<%= @moment.image_url %>
	</p>

	<p>
	<strong>Audio url:</strong>
	<%= @moment.audio_url %>
	</p> 

	<br/>
	<%= link_to 'Edit', edit_moment_path(@moment) %> |
	<%= link_to 'Back', moments_path %>

	<div class="card">
		<div class="imgBox">
			<div class="bark"></div>
			<img src="https://image.ibb.co/fYzTrb/lastofus.jpg">
		</div>
		<div class="details">
			<h4 class="color1"><%= @moment.title %></h2>
			<h4 class="color2 margin">(HAPPY BIRTHDAY)</h3>
			<p>Dear <%= @moment.to_name %>,</p>
			<p>Let's see.. .</p>
			<p>You’re never around, you</p>
			<p>hate the music I’m into, you</p>
			<p>practically despise the movies I</p>
			<p>like, and yet somehow you still</p>
			<p>manage to be the best dad every year.</p>
			<p>How do you do that? :)</p>
			<p class="text-right">Happy Birthday, <%= @moment.to_name %>!</p>
			<p class="text-right">♥<%= @moment.from_name %></p>
		</div>
	</div>

<% end %>